#Permanent settings for the site
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# used ruby gems for building this jekyll based site
gems:
  - jekyll-mermaid              # allows mermaid diagrams included in ```mermaid blocks in md
plugins:
  - jekyll-datapage-generator   # TODO investigate and document why this is here
  - jemoji    

# Configuration settings for the jekyll theme
base_url: "" # Base URI for your site, e.g. http://example.com/test-repo/ => for development leave empty for gh-pages fill in the name of the repo of not the main gh-pages repo
title: "Read the LOD" # Title of your site
share_enabled: false # Enables global share buttons to twitter (X), facebook, printer, email, linkedIn | default true
logo: "/assets/media/img/partners/rtlp_logo.svg" # Logo used for your site
social_media:
  - name: "github"
    url: "https://github.com/readthelod"